spring:
  application:
    name: mall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tMojJ2baCmgV7QCuKMd
      secret-key: i0dBM55lKd6uOSy4szZDfeAK4x8Ctn
      oss:
        endpoint: oss-cn-zhangjiakou.aliyuncs.com
        bucket: gumt-mall
logging:
  level:
    top.gumt.mall.product: debug
server:
  port: 30000
